spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/project_microservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    application:
         name: Config-default
  
 eureka:
       instance:
          client:
           serverUrl.defaultZone=http://localhost:8761/eureka/

      
