 spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chandrika-Patel/practice-microservices

eureka:
    client:
       register:
              with-eureka: false 
              fetch-registry: false          
          
