spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/project_microservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    spring:
   application:
       name:  "Config dev"
